# --- Site Settings ---
title: "Marek Jungwirth | Portfolio"
description: "Portfolio of data analysis, Python, SQL, and on-chain data projects."
url: "https://marekjungwirth.github.io"
baseurl: "" # Musí být prázdné!

# --- Theme ---
remote_theme: b2a3e8/jekyll-theme-console

# --- Header Menu Links ---
# Tímto říkáme hlavičce, jaké odkazy má zobrazit
header_pages:
  - index.md
  - about.md
  - projects.md
  - tools.md

# --- Build Settings ---
plugins:
  - jekyll-seo-tag
  
markdown: kramdown
permalink: /:categories/:title/

# --- Theme Options ---
# Můžeš si pohrát se stylem, pokud chceš. "hacker" je klasika.
style: dark # Možnosti: dark (default), light, hacker, nord
