# --- Site Settings ---
title: "Marek Jungwirth | Portfolio"
description: "Portfolio of data analysis, Python, SQL, and on-chain data projects."
url: "https://marekjungwirth.github.io"
baseurl: ""

# --- Header Menu Links ---
header_pages:
  - index.md
  - about.md
  - projects.md
  - tools.md

# --- Build Settings ---
plugins:
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - assets/css

theme: jekyll-theme-console

markdown: kramdown

# lepší a bezpečnější než vlastní pattern
permalink: pretty

# --- Theme Options ---
style: dark
